### ISSUE TITLE
Panic from `snd_pcm_hw_params_set_format`

### ISSUE THREAD

**Issue by andrewbaxter** [tesselode/kira#104]
I get this error:
```
thread '<unnamed>' panicked at /home/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/kira-0.8.7/src/manager/backend/cpal/desktop/stream_manager.rs:69:59:
called `Result::unwrap()` on an `Err` value: BuildStreamError(BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_hw_params_set_format' failed with error 'Invalid argument (22)'" } })
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1102:23
   4: kira::manager::backend::cpal::desktop::stream_manager::StreamManager::start::{{closure}}
             at /home/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/kira-0.8.7/src/manager/backend/cpal/desktop/stream_manager.rs:69:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
and no sound plays.

Sorry if this version of kira is too old - I'm using this with bevy and I can't update bevy atm so it's hard to update kira, in case this was fixed in a later version.

I'm on arch with pipewire.  I do a lot of audio stuff and this (and [rodio](https://github.com/RustAudio/rodio/issues/448), fwiw) are the only things that seem to have audio issues.

**Comment by tesselode** [comment]
I think this is probably a cpal issue because Kira doesn't interface with ALSA directly. Maybe open an issue in the cpal repo?
